src/Marton/PortfolioBundle/Entity/Photography.php
<?php

namespace Marton\PortfolioBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Marton\PortfolioBundle\Repository\PhotographyRepository")
 * @ORM\Table(name="tbl_photography")
 */

class Photography{


    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $dir_path;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $pic_path;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    protected $text;

    /**
     * @ORM\Column(type="integer")
     */
    protected $year;

    /**
     * @ORM\Column(type="integer")
     */
    protected $order;

    public function setOrder($order)
    {
        $this->order = $order;
    }

    public function getOrder()
    {
        return $this->order;
    }

    public function setYear($year)
    {
        $this->year = $year;
    }

    public function getYear()
    {
        return $this->year;
    }

    public function setText($text)
    {
        $this->text = $text;
    }

    public function getText()
    {
        return $this->text;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getDate()
    {
        return $this->date;
    }

    public function setDirPath($dir_path)
    {
        $this->dir_path = $dir_path;
    }

    public function getDirPath()
    {
        return $this->dir_path;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setPicPath($pic_path)
    {
        $this->pic_path = $pic_path;
    }

    public function getPicPath()
    {
        return $this->pic_path;
    }
}

src/Marton/PortfolioBundle/Resources/views/Default/Pages/biography.html.twig
{% extends 'MartonPortfolioBundle:Default:index.html.twig' %}

{% block body_id %}{% endblock %}

{% block active_tab_bio %} active{% endblock %}

{% block dash_line %}
    <div class="dash_line"></div>
{% endblock %}

{% block sub_dashboard %}{% endblock %}

{% block content %}

    <div class="content shadow">
        <div class="bio">

            <div class="bio_projects">

                <h1>My projects</h1>

                <div id="project_container">

                    {% for project in projects %}
                        <div class="project_entry project_entry_closed" id="project_entry_{{ project.id }}">
                            <div class="project_header" style="background: url({{ asset('bundles/martonportfolio/images/projects/' ~ project.picture) }}) no-repeat;" data-state="closed">
                                <h2 class="p_title">{{ project.title }}</h2>
                                <p class="p_subheader">{{ project.subheader }}</p>
                                <div class="project-info">
                                    {% if project.bitBucketLink is not null %}
                                        <a class="a-project-info" href="{{ project.bitBucketLink }}"  target="_blank">
                                            <img src="{{ asset('bundles/martonportfolio/images/src/bitbucket.png') }}" width="20" height="20"/>
                                            <p>BitBucket</p>
                                        </a>
                                    {% endif %}
                                    {% if project.screenshotsLink is not null %}
                                        <a class="a-project-info" href="{{ project.screenshotsLink }}"  target="_blank">
                                            <img src="{{ asset('bundles/martonportfolio/images/src/screenshots.png') }}" width="20" height="20"/>
                                            <p>Screenshots</p>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                            <p class="p_text">{{ project.text | raw }}</p>
                        </div>

                        <hr>
                    {% endfor %}

                </div>

            </div>

            <div class="bio_about">

                <h1 class="about_title">About me</h1>

                <div class="about_short">

                    {% for key,value in personal_details %}

                        <div class="about_row">
                            <div class="row_title">
                                {{ key }}
                            </div>
                            <div class="row_value">
                                {{ value }}
                            </div>
                        </div>

                    {% endfor %}

                </div>

                <div class="bio_about_pic"></div>

                <div class="about_long">
                    <p>I'm a 3rd year Software Engineering student with a strong passion towards programming, supercars and
                        photography.</p>
                    <br>
                    <p>While currently in progress for a first class degree, I also work on my own projects to keep up with
                       the latest technology and best practices in computing. </p>
                    <br>
                </div>

            </div>

            <br>
            <br>
            <hr>

        </div>

    </div>

{% endblock %}

{% block background %}



    <script>

        ProjectBrowserModule.init();

        var background_arr = [
            "{{ asset('bundles/martonportfolio/images/background/IMG_2763.jpg') }}"
        ];

        BackgroundGalleryModule.init(background_arr);

        preloadImages(background_arr).done(function(images){
            BackgroundGalleryModule.create()
                                   .shade()
                                   .start()
                                   .pause();
        });

    </script>


{% endblock %}

src/Marton/PortfolioBundle/Resources/views/Default/Pages/contact.html.twig
{% extends 'MartonPortfolioBundle:Default:index.html.twig' %}

{% block body_id %}class="theme_light"{% endblock %}

{% block active_tab_contact %} active{% endblock %}

{% block dash_line %}
    <div class="dash_line"></div>
{% endblock %}

{% block sub_dashboard %}{% endblock %}

{% block content %}

    <div class="content right">

        <div class="contact shadow">

            <div class="contact_tile left">

                <div class="contact_header">
                    <h1>Details: </h1>
                </div>
                <p>Thank you for visiting my portfolio page.</p>
                <p>Please feel free to contact me with questions or feedback.</p>

                <div class="contact_info">
                    <div>
                        <p class="title">E-mail: </p>
                        <p class="value"><script>var lhs = "martonszeles93";var rhs = "gmail.com";document.write(lhs+"@"+rhs);</script></p>
                    </div>

                    <div>
                        <p class="title">Flickr: </p>
                        <a class="value" href="https://www.flickr.com/photos/marleton" target="_blank">www.flickr.com/marleton</a>
                    </div>
                </div>

            </div>

            <div class="contact_tile">

                {% if form is defined %}

                    <div class="contact_header">
                        <h1>Send a message: </h1>
                    </div>


                    <div class="contact_form">

                        {{ form_start(form) }}
                        {{ form_errors(form) }}

                        {{ form_row(form.name) }}
                        {{ form_row(form.email) }}
                        {{ form_row(form.subject) }}
                        {{ form_row(form.message) }}
                        {{ form_end(form) }}

                    </div>

                {% endif %}

                {% if success is defined %}

                    <div class="contact_success">
                        <h4>Message successfully sent!</h4>
                        <p>I will aim to reply in the next 24 hours.</p>
                    </div>

                {% endif %}

            </div>

        </div>

    </div>

    <script>
        var background_arr = ["{{ asset('bundles/martonportfolio/images/background/IMG_8695.jpg') }}"];

        BackgroundGalleryModule.init(background_arr);
        preloadImages(background_arr).done(function(images){
            BackgroundGalleryModule.create()
                                   .start()
                                   .pause();
        });
    </script>
{% endblock %}

{% block background %}

{% endblock %}

src/Marton/PortfolioBundle/Resources/views/Default/Pages/drawing.html.twig
{% extends 'MartonPortfolioBundle:Default:index.html.twig' %}

{% block body_id %}class="theme_dark"{% endblock %}

{% block active_tab_drawing %} active{% endblock %}

{% block dash_line %}
    <div class="dash_line"></div>
{% endblock %}

{% block sub_dashboard %}{% endblock %}

{% block content %}

    <div class="content shadow">
        <div class="drawing_div">

            {% set counter = 0 %}
            {% for drawing in drawings %}

                <div class="drawing_frame image-rotator" id="{{ counter }}" name="jump">
                    <div class="drawing_title">
                        <h3>{{ drawing.name }}</h3>
                        <p>{{ drawing.year }}</p>
                    </div>
                    <img src="{{ asset('bundles/martonportfolio/images/drawings/thumbnails') }}/{{ drawing.thumbnail }}"/>

                </div>

                {% set counter = counter + 1 %}

            {% endfor %}

        </div>

    </div>

{% endblock %}

{% block background %}

    <script>
        var background_arr = [];

        var prefix = "{{ asset('bundles/martonportfolio/images/drawings') }}";

        {% for drawing in drawings %}
            background_arr.push(prefix + "/{{ drawing.image }}");
        {% endfor %}

        preloadImages(background_arr);

        BackgroundGalleryModule.init(background_arr, {controlPanel:true, hasExit:true});
    </script>

{% endblock %}

src/Marton/PortfolioBundle/Resources/views/Default/Pages/home.html.twig
{% extends 'MartonPortfolioBundle:Default:index.html.twig' %}

{% block content %}

{% endblock %}

{% block background %}

    <script>
        // To be called on each page separately
        var background_arr = [
            "{{ asset('bundles/martonportfolio/images/background/IMG_0680.jpg') }}",
            "{{ asset('bundles/martonportfolio/images/photography/tvr_t350_c/IMG_1136.jpg') }}",
            "{{ asset('bundles/martonportfolio/images/photography/unimog/IMG_8695.jpg') }}",
            "{{ asset('bundles/martonportfolio/images/photography/macro/IMG_1574.jpg') }}",
            "{{ asset('bundles/martonportfolio/images/photography/huracan_launch/IMG_1356.jpg') }}"];

        BackgroundGalleryModule.init(background_arr, {controlPanel:true});

        preloadImages(background_arr).done(function(images){
            BackgroundGalleryModule.create()
                                   .start();
        });

    </script>


{% endblock %}

src/Marton/PortfolioBundle/Resources/views/Default/Pages/photography.html.twig
{% extends 'MartonPortfolioBundle:Default:index.html.twig' %}

{% block body_id %}class="theme_dark"{% endblock %}

{% block active_tab_photo %} active{% endblock %}

{% block dash_line %}
    <div class="dash_line"></div>
{% endblock %}

{% block sub_dashboard %}
{% endblock %}

{% block content %}

    <div class="content shadow">
        <div class="photo_div">

            {% for album in albums %}

                <div class="album_frame">
                    <a href="photography/{{ album.dirPath }}">
                        <img class="album_image" src="{{ asset('bundles/martonportfolio/images/photography') }}/{{ album.dirPath }}/thumbnails/{{ album.picPath }}"/>
                    </a>
                    <div class="album_title_background"></div>
                    <a class="album_title_text" href="photography/{{ album.dirPath }}">{{ album.name }}</a>

                </div>

            {% endfor %}

        </div>

    </div>

{% endblock %}

{% block background %}

{% endblock %}